deployment:
    name: flask-app
    image: 661308776255.dkr.ecr.us-east-1.amazonaws.com/flask
    tag: latest
    replicas: 2
    port: 5000
    env: dev
    domain: ev4o.com
    region: us-east-1

service:
   port: 80
   nodeport: 30000
   targetport: 5000